// Generated by CoffeeScript 1.8.0
var nodemailer;

nodemailer = require("nodemailer");

exports.index = function(req, res) {
  res.render("index", {
    title: "send to e-mail",
    para: req.param("para"),
    asunto: req.param("asunto"),
    texto: req.param("texto")
  });
};

exports.enviar = function(req, res) {
  var mailOptions, smtpTransport;
  smtpTransport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
      user: "logistica@icrperusa.com",
      pass: "MGisla2011"
    }
  });
  mailOptions = {
    from: "Logistica ICR PERU S.A. ✔ <logistica@icrperusa.com>",
    to: req.body.email,
    subject: req.body.asunto,
    html: req.body.texto
  };
  smtpTransport.sendMail(mailOptions, function(error, response) {
    if (error) {
      console.log(error);
      res.render("error", {
        title: "Error al enviar el mail"
      });
    } else {
      console.log("Message sent: " + response.message);
      res.render("enviado", {
        title: "El mensaje fue enviado"
      });
    }
  });
};

exports.envelop = function(request, response) {
  var authProperty, emailOptions, fromProperty, smtpTransport;
  console.log(request.param("notdounsdf"));
  authProperty = new Object;
  fromProperty = "";
  if (request.param("pwdmailer") !== void 0) {
    console.log("success");
    fromProperty = "" + (request.param("name")) + " <" + (request.param("email")) + "> ✔";
    authProperty = {
      user: request.param("email"),
      pass: request.param("pwdmailer")
    };
  } else {
    fromProperty = "Logistica ICR PERU S.A. ✔ <logistica@icrperusa.com>";
    authProperty = {
      user: "logistica@icrperusa.com",
      pass: "MGisla2011"
    };
  }
  smtpTransport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: authProperty
  });
  emailOptions = {
    from: fromProperty,
    to: request.param("forsb"),
    subject: request.param("issue"),
    html: request.param("body")
  };
  smtpTransport.sendMail(emailOptions, function(error, result) {
    if (error) {
      console.error(error);
      response.render("error", {
        title: "Error al enviar mensaje"
      });
    } else {
      console.log("Message sent: " + result.message);
      response.render("enviado", {
        title: "El mensaje fue enviado"
      });
    }
  });
};
