// Generated by CoffeeScript 1.10.0
var http, path, port, sendMails, server, sys, url;

http = require('http');

path = require('path');

sys = require('sys');

url = require('url');

port = 8000;

server = null;

server = http.createServer(function(request, response) {
  var url_parts;
  url_parts = url.parse(request.url);
  switch (url_parts.pathname) {
    case '/':
      sendMails(url_parts.pathname, request, response);
      break;
    default:
      null;
  }
}).on('error', function(e) {
  console.log("Got error: " + e.message);
});

sendMails = function(_url, req, res) {
  console.log(req.query);
  console.log(url.parse(req.url, true).query);
  res.writeHead(200, {
    'Content-Type': 'application/json'
  });
  res.write("{'status': false}");
  res.end();
};

server.listen(port);

sys.puts("Server running at in port 8000 localhost");
